opt_in_rules:
  - attributes
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - control_statement
  #- custom_rules
  - cyclomatic_complexity
  - dynamic_inline
  - empty_count
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - file_length
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - implicit_getter
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - mark
  - missing_docs
  - nesting
  - nimble_operator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - private_unit_test
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - redundant_string_enum_value
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_docs
  - valid_ibinspectable
  - variable_name
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
  - weak_delegate

disabled_rules:
  - file_header
  - missing_docs
  - number_separator
  - sorted_imports

included:
  - SwiftyVIPERExample
  - SwiftyVIPERExampleTests

excluded:
  - Pods
  - Carthage

private_outlet:
  allow_private_set: true
