language: objective-c
osx_image: xcode8
script:
  - xcodebuild -version
  - xcodebuild -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF ios
