language: objective-c
osx_image: xcode8

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=SwiftyVIPER.xcodeproj
  - IOS_FRAMEWORK_SCHEME="SwiftyVIPERiOS"
  - IOS_SDK=iphonesimulator10.0
  matrix:
  - DESTINATION="OS=9.0,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"

script:
- brew unlink swiftlint
- brew install swiftlint
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES ENABLE_TESTABILITY=YES build test

notifications:
  email: false

after_success:
- bash <(curl -s https://codecov.io/bash)
